import { renderCharts, clearCharts } from './charts.js';

const root = new URL(document.body.dataset.root || '../../', location.href);
const engine = document.body.dataset.engine || 'chartjs';
const url = path => new URL(path, root).href;
const icon = (name, size=18) => {
  const paths={grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',chart:'<path d="M4 19h17M7 15V9m5 6V4m5 11v-5"/>',box:'<path d="m12 3 9 5-9 5-9-5 9-5Z M3 8v9l9 5 9-5V8M12 13v9M7 5l10 6"/>',check:'<path d="m5 12 4 4L19 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',book:'<path d="M3 3h7l2 2 2-2h7v17h-7l-2 2-2-2H3V3ZM12 5v17"/>'};
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.chart}</svg>`;
};
document.getElementById('app').innerHTML=`
<a class="skip-link" href="#overview" style="position:absolute;left:-10000px">ข้ามไปเนื้อหา</a>
<aside class="side"><a class="brand" href="${url('index.html')}"><span class="brand-icon">${icon('chart',25)}</span><span>retail<span style="color:#dbe99e">.</span><small>DATA EXPLORER</small></span></a><div class="side-label">WORKSPACE / 01</div><nav aria-label="เมนูหลัก"><a href="#overview" class="active">${icon('grid')} ภาพรวมยอดขาย</a><a href="#products">${icon('box')} สำรวจสินค้า</a><a href="#quality">${icon('check')} คุณภาพข้อมูล</a><a href="#methodology">${icon('book')} กระบวนการวิเคราะห์</a></nav><div class="side-bottom"><strong>Real data. Clear decisions.</strong>Online Retail · UCI<br>ธ.ค. 2010 — ธ.ค. 2011<br><br>Data Visualization Technology<br>Interactive project</div></aside>
<div id="loading" class="loading-line" aria-hidden="true"></div>
<main class="main" id="overview"><header class="topbar"><div><span class="mobile-brand">retail.</span><span class="crumb">Workspace <span style="padding:0 10px">/</span> <strong>Sales analytics</strong></span></div><div class="top-actions"><span class="dataset-status"><i class="dot"></i>UCI · Historical dataset</span><button class="icon-button" id="theme" title="สลับโหมดสว่าง/มืด" aria-label="สลับโหมดสว่าง/มืด" aria-pressed="false">${icon('sun')}</button><button class="btn" id="export" disabled>${icon('download',15)} Export CSV</button></div></header>
<section class="heading"><div><div class="eyebrow">RETAIL INTELLIGENCE</div><h1>มองยอดขายให้เห็นมากกว่าเดิม<span style="color:#86a34f">.</span></h1><p>สำรวจแนวโน้ม สินค้าขายดี และตลาดของร้านค้าออนไลน์ ด้วยข้อมูลธุรกรรมจริง</p></div><nav class="engine-tabs" aria-label="เลือกไลบรารีกราฟ"><a href="${url('web/chartjs/index.html')}" class="${engine==='chartjs'?'active':''}">Chart.js</a><a href="${url('web/plotly/index.html')}" class="${engine==='plotly'?'active':''}">Plotly.js</a></nav></section>
<div id="error" class="error" role="alert" hidden></div>
<form id="filters" class="toolbar" aria-label="ตัวกรองข้อมูล"><div class="field"><label for="country">ประเทศ / Market</label><select id="country"><option value="">ทุกประเทศ</option></select></div><div class="field"><label for="from">ตั้งแต่เดือน</label><select id="from"></select></div><div class="field"><label for="to">ถึงเดือน</label><select id="to"></select></div><label class="switch"><input type="checkbox" id="exclude"> ไม่รวมรายการที่ติดธง Outlier</label><button type="button" class="btn" id="reset">ล้างตัวกรอง</button></form>
<div class="status-row"><span id="status" role="status" aria-live="polite">กำลังโหลดข้อมูล…</span><span class="notice" id="partial">ธ.ค. 2011 มีข้อมูลถึงวันที่ 9 เท่านั้น</span></div>
<section class="kpis" aria-label="ตัวชี้วัด"><article class="kpi featured rise"><div class="kpi-head">ยอดขายก่อนหักยกเลิก<span class="symbol">£</span></div><div class="kpi-value" id="kpi-sales">—</div><div class="kpi-foot"><span class="badge">GROSS SALES</span><span>สกุลเงิน GBP</span></div></article><article class="kpi rise"><div class="kpi-head">ยอดสุทธิ<span class="symbol">${icon('chart',15)}</span></div><div class="kpi-value" id="kpi-net">—</div><div class="kpi-foot" id="net-foot">ยอดขาย + มูลค่ารายการยกเลิก</div></article><article class="kpi rise"><div class="kpi-head">จำนวนสินค้าที่ขาย<span class="symbol">${icon('box',15)}</span></div><div class="kpi-value" id="kpi-units">—</div><div class="kpi-foot">หน่วยสินค้า · ไม่ใช่จำนวนคำสั่งซื้อ</div></article><article class="kpi rise"><div class="kpi-head">สินค้าที่มียอดขาย<span class="symbol">${icon('grid',15)}</span></div><div class="kpi-value" id="kpi-products">—</div><div class="kpi-foot" id="products-foot">นับรหัสสินค้าไม่ซ้ำ</div></article></section>
<div class="section-title"><h2>ภาพรวมการเติบโต</h2><span id="engine-label">Interactive charts · ${engine==='chartjs'?'Chart.js':'Plotly.js'}</span></div>
<section class="chart-grid" aria-label="กราฟวิเคราะห์"><article class="panel"><div class="panel-head"><div><h3>ยอดขายในแต่ละเดือน</h3><p>เปรียบเทียบยอดขายกับยอดสุทธิ · GBP</p></div><span class="panel-tag">01 / LINE</span></div><div class="chart" id="trend" role="img" aria-label="กราฟเส้นยอดขายรายเดือน"></div><div class="chart-note">ชี้กราฟเพื่อดูยอดจริง · คลิกเดือนเพื่อเจาะดูข้อมูลเดือนนั้น</div></article><article class="panel"><div class="panel-head"><div><h3>ตลาดที่สร้างยอดขาย</h3><p>สัดส่วนยอดขายบวกตามประเทศ</p></div><span class="panel-tag">02 / DONUT</span></div><div class="chart" id="market" role="img" aria-label="กราฟโดนัทสัดส่วนประเทศ"></div><div class="chart-note">5 ประเทศแรก + ประเทศอื่น ๆ · คลิกประเทศเพื่อกรองข้อมูล</div></article><article class="panel"><div class="panel-head"><div><h3>10 สินค้าขายดี</h3><p>รวมรหัสค่าจัดส่ง/ค่าบริการ · GBP</p></div><span class="panel-tag">03 / BAR</span></div><div class="chart" id="ranking" role="img" aria-label="กราฟแท่งสินค้า 10 อันดับ"></div><div class="chart-note">ใช้รหัสสินค้าเป็นตัวระบุ · ชี้เพื่อดูชื่อเต็ม หรือคลิกดูรายละเอียด</div></article><article class="panel"><div class="panel-head"><div><h3>ราคา × ปริมาณการขาย</h3><p>หนึ่งจุดต่อรหัสสินค้า · แสดงสินค้าที่ขายทั้งหมด</p></div><span class="panel-tag">04 / SCATTER</span></div><div class="chart" id="scatter" role="img" aria-label="กราฟกระจายราคาเฉลี่ยกับจำนวนขาย"></div><div class="chart-note">ราคาเฉลี่ยถ่วงน้ำหนัก × จำนวนขาย · สเกล log ทั้งสองแกน</div></article></section>
<div class="section-title" id="products"><h2>เจาะลึกสินค้า</h2><span>ค้นหา · เรียงลำดับ · ดาวน์โหลด</span></div><section class="bottom-grid"><article class="panel table-panel"><div class="panel-head"><div><h3>รายการสินค้าตามตัวกรอง</h3><p id="table-caption">คลิกชื่อสินค้าเพื่อดูรายละเอียด</p></div><input id="search" class="search" type="search" placeholder="ค้นหาชื่อหรือรหัสสินค้า…" aria-label="ค้นหาสินค้าในตาราง"></div><div class="table-wrap"><table><thead><tr><th>#</th><th>สินค้า</th><th class="numeric"><button class="product-link" data-sort="units">จำนวน ↕</button></th><th class="numeric"><button class="product-link" data-sort="sales">ยอดขาย GBP ↕</button></th><th class="numeric"><button class="product-link" data-sort="net">สุทธิ GBP ↕</button></th></tr></thead><tbody id="table-body"></tbody></table></div><div class="pagination"><span id="page-label"></span><div><button class="btn" id="prev" aria-label="หน้าก่อนหน้า">←</button> <button class="btn" id="next" aria-label="หน้าถัดไป">→</button></div></div></article><aside class="panel insight"><div class="eyebrow">FROM DATA TO INSIGHT</div><h3 id="insight-title">อ่านเรื่องราว<br>จากยอดขาย</h3><p id="insight-text">ตัวเลขส่วนนี้จะเปลี่ยนตามประเทศและช่วงเวลาที่เลือก</p><div class="insight-stat" id="insight-value">—</div><p>สัดส่วนยอดขายของสินค้าขายดีอันดับ 1</p><hr class="insight-line"><p>ยอดขายสูงไม่ได้แปลว่ากำไรสูง ข้อมูลชุดนี้ไม่มีต้นทุนสินค้า</p><a href="#quality" class="btn">เข้าใจข้อมูลก่อนตัดสินใจ ${icon('arrow',14)}</a></aside></section>
<section class="panel quality" id="quality"><div class="panel-head"><div><div class="eyebrow">DATA WITH CONTEXT</div><h3>ข้อมูลที่เชื่อถือได้ เริ่มจากการตรวจสอบ</h3><p>ภาพรวมคุณภาพข้อมูลทั้งชุด · ไม่เปลี่ยนตามตัวกรอง</p></div><span class="badge">AUDIT TRAIL INCLUDED</span></div><div class="quality-grid"><div class="quality-item"><strong>541,909</strong>แถวในข้อมูลต้นฉบับ</div><div class="quality-item"><strong>5,268</strong>แถวซ้ำที่แยกเก็บ</div><div class="quality-item"><strong>2,512</strong>แถวที่ต้องตรวจสอบ</div><div class="quality-item"><strong>534,129</strong>รายการขาย + ยกเลิกพร้อมวิเคราะห์</div></div><p>CustomerID ที่ว่างยังคงเป็นค่าว่างเพื่อไม่สร้างลูกค้าสมมติ รายการยกเลิกเก็บมูลค่าติดลบ และ Outlier ถูกติดธงโดยไม่ลบอัตโนมัติ รหัสค่าจัดส่งและค่าบริการยังรวมอยู่ในยอดขาย การแยกแถวซ้ำเป็นสมมติฐานการวิเคราะห์ที่ตรวจคืนได้จากไฟล์ audit</p></section>
<section class="panel quality" id="methodology"><div class="panel-head"><div><div class="eyebrow">THE PROCESS</div><h3>จากข้อมูลดิบ สู่คำตอบทางธุรกิจ</h3><p>กระบวนการวิเคราะห์ตามกรอบ CRISP-DM</p></div></div><div class="method-grid"><div class="method-step"><b><span class="method-num">01</span> Business understanding</b><p>ยอดขายเปลี่ยนอย่างไร สินค้าใดขายดี และประเทศใดสร้างรายได้หลัก</p></div><div class="method-step"><b><span class="method-num">02</span> Data understanding</b><p>541,909 รายการ 8 คอลัมน์ ตรวจ missing, duplicate, outlier และรูปแบบข้อมูล</p></div><div class="method-step"><b><span class="method-num">03</span> Data preparation</b><p>แยกแถวซ้ำ ปรับรูปแบบ แยก sale / cancellation / review และรักษาข้อมูลต้นฉบับ</p></div><div class="method-step"><b><span class="method-num">04</span> Modeling / analysis</b><p>สรุปเชิงพรรณนาตามเดือน ประเทศ และสินค้า ใช้กราฟ 4 ประเภท ไม่สร้างโมเดลพยากรณ์</p></div><div class="method-step"><b><span class="method-num">05</span> Evaluation</b><p>เทียบยอด CSV กับ JSON และตรวจตัวกรองจากข้อมูลจริง คำนวณเงินเป็น milli-GBP</p></div><div class="method-step"><b><span class="method-num">06</span> Deployment</b><p>เว็บ static สองเวอร์ชัน รองรับมือถือ พร้อมโครงสร้างสำหรับ GitHub Pages</p></div></div><div class="source-links"><a class="btn" href="https://archive.ics.uci.edu/dataset/352/online+retail" target="_blank" rel="noopener">แหล่งข้อมูล UCI ↗</a><a class="btn" href="${url('CLEANING_REPORT.md')}">บันทึกการทำความสะอาด</a><a class="btn" href="${url('docs/Process_Report.pdf')}">รายงาน PDF ${icon('download',14)}</a><a class="btn" href="${url('data/audit/quality_report.json')}">ผลตรวจข้อมูล JSON</a></div></section><footer class="footer"><span>retail. / Data Visualization Technology</span><span>Source: Chen, D. (2015) · UCI Online Retail · CC BY 4.0 · GBP</span></footer></main><dialog id="detail"><button class="icon-button close" id="close-dialog" aria-label="ปิดรายละเอียด">✕</button><div class="eyebrow">PRODUCT DETAIL</div><h2 id="detail-title"></h2><p id="detail-code"></p><dl id="detail-values"></dl><p style="color:var(--muted);font-size:11px">คำนวณจากประเทศและช่วงเวลาที่เลือก ราคาคือค่าเฉลี่ยถ่วงน้ำหนักด้วยจำนวนขาย</p></dialog><div class="toast" id="toast" role="status" hidden></div>`;

const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2}).format(n/1000), num=n=>new Intl.NumberFormat('en-GB').format(n), compact=n=>new Intl.NumberFormat('en-GB',{notation:'compact',maximumFractionDigits:2}).format(n);
const labelMonth=m=>new Intl.DateTimeFormat('th-TH',{month:'short',year:'2-digit'}).format(new Date(Number(m.slice(0,4)),Number(m.slice(5))-1,1));
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let dashboard, manifest, current, view=[], page=0, sort='sales', descending=true, version=0, toastTimer;
let renderQueue=Promise.resolve();
const cache=new Map(), pageSize=8;
async function json(path){const r=await fetch(url(path));if(!r.ok)throw new Error(`${path} (HTTP ${r.status})`);return r.json();}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2600);}
function busy(on){$('loading').hidden=!on;$('export').disabled=on;$('app').setAttribute('aria-busy',String(on));}
async function getMonth(m){if(!cache.has(m.month)){const promise=json('web-data/'+m.path).catch(e=>{cache.delete(m.month);throw e;});cache.set(m.month,promise);}return cache.get(m.month);}

export function aggregate(rows, country='', exclude=false, names={}){
  let sales=0,cancel=0,units=0,lines=0,cancelLines=0;
  const months=new Map(),countries=new Map(),products=new Map();
  for(const r of rows){const [month,market,code,outlier,s,c,u,l,cl]=r;if((country&&market!==country)||(exclude&&outlier))continue;
    sales+=s;cancel+=c;units+=u;lines+=l;cancelLines+=cl;
    if(!months.has(month))months.set(month,{month,sales:0,net:0});const mt=months.get(month);mt.sales+=s;mt.net+=s+c;
    countries.set(market,(countries.get(market)||0)+s);
    if(!products.has(code))products.set(code,{code,name:names[code]||code,sales:0,cancel:0,units:0,lines:0});
    const pr=products.get(code);pr.sales+=s;pr.cancel+=c;pr.units+=u;pr.lines+=l;
  }
  const ps=[...products.values()].map(p=>({...p,net:p.sales+p.cancel,price:p.units?p.sales/p.units/1000:0})).sort((a,b)=>b.sales-a.sales||a.code.localeCompare(b.code));
  return {sales,cancel,net:sales+cancel,units,lines,cancelLines,products:ps,months:[...months.values()].sort((a,b)=>a.month.localeCompare(b.month)),countries:[...countries].filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]),activeProducts:ps.filter(p=>p.sales>0).length};
}
async function update(){
  const token=++version;busy(true);$('error').hidden=true;
  if($('from').value>$('to').value){$('to').value=$('from').value;toast('ปรับเดือนสิ้นสุดให้ตรงกับเดือนเริ่มต้น');}
  const start=$('from').value,end=$('to').value,country=$('country').value,exclude=$('exclude').checked;
  $('status').textContent='กำลังสรุปข้อมูลตามตัวกรอง…';
  try{
    const months=manifest.months.filter(x=>x.month>=start&&x.month<=end);
    const groups=await Promise.all(months.map(getMonth));if(token!==version)return;
    const names=Object.fromEntries(dashboard.products.map(p=>[p.StockCode,p.Description]));
    current=aggregate(groups.flat(),country,exclude,names);
    for(const m of months)if(!current.months.some(x=>x.month===m.month))current.months.push({month:m.month,sales:0,net:0});
    current.months.sort((a,b)=>a.month.localeCompare(b.month));
    $('kpi-sales').textContent='£'+compact(current.sales/1000);$('kpi-sales').title=money(current.sales);
    $('kpi-net').textContent='£'+compact(current.net/1000);$('kpi-net').title=money(current.net);
    $('kpi-units').textContent=num(current.units);$('kpi-products').textContent=num(current.activeProducts);
    $('net-foot').textContent=`หักยกเลิก ${money(Math.abs(current.cancel))}`;
    $('products-foot').textContent=`จากรายการขาย ${num(current.lines)} แถว`;
    $('status').textContent=`${country||'ทุกประเทศ'} · ${labelMonth(start)} – ${labelMonth(end)} · ${num(current.lines+current.cancelLines)} รายการ${exclude?' · ไม่รวม Outlier':''}`;
    $('partial').hidden=!(start<='2011-12'&&end>='2011-12');
    page=0;updateTable();updateInsight();
    const snapshot=current;
    renderQueue=renderQueue.catch(()=>{}).then(()=>token===version?renderCharts(engine,snapshot,{month:labelMonth,money,product:openProduct,country:selectCountry,selectMonth,theme:document.body.classList.contains('dark')}):undefined);
    await renderQueue;
    if(token!==version)return;
    window.__dashboardState={sales:current.sales,net:current.net,units:current.units,lines:current.lines,productCount:current.activeProducts,country,start,end,exclude,ready:true};
  }catch(e){if(token!==version)return;$('error').hidden=false;$('error').textContent=`โหลดข้อมูลไม่สำเร็จ: ${e.message} กรุณาเปิดผ่าน http://localhost:8000 หรือ GitHub Pages แล้วลองเปลี่ยนตัวกรองอีกครั้ง`;$('status').textContent='ยังไม่สามารถแสดงผลครบได้';window.__dashboardState={ready:false,error:e.message};}
  finally{if(token===version)busy(false);}
}
function updateInsight(){const top=current.products.find(p=>p.sales>0);$('insight-title').textContent=top?'สินค้าที่สร้างยอดขายสูงสุด':'ไม่พบรายการขาย';$('insight-text').textContent=top?`${top.name} (${top.code}) ทำยอดขาย ${money(top.sales)} จากสินค้าที่ขาย ${num(top.units)} หน่วย`:'ลองเปลี่ยนประเทศ ช่วงเวลา หรือตัวเลือก Outlier';$('insight-value').textContent=top&&current.sales?(100*top.sales/current.sales).toFixed(1)+'%':'—';}
function updateTable(){if(!current)return;const query=$('search').value.trim().toLowerCase();view=current.products.filter(p=>(p.name+' '+p.code).toLowerCase().includes(query)).sort((a,b)=>(descending?b[sort]-a[sort]:a[sort]-b[sort])||a.code.localeCompare(b.code));const maxPage=Math.max(0,Math.ceil(view.length/pageSize)-1);page=Math.min(page,maxPage);const rows=view.slice(page*pageSize,(page+1)*pageSize);$('table-body').innerHTML=rows.length?rows.map((p,i)=>`<tr><td class="rank">${page*pageSize+i+1}</td><td><button class="product-link" data-product="${escapeHTML(p.code)}"><span class="product-name" style="display:block" title="${escapeHTML(p.name)}">${escapeHTML(p.name)}</span><span class="product-code">${escapeHTML(p.code)}</span></button></td><td class="numeric">${num(p.units)}</td><td class="numeric">${money(p.sales).replace('£','')}</td><td class="numeric">${money(p.net).replace('£','')}</td></tr>`).join(''):'<tr><td colspan="5">ไม่พบสินค้าที่ตรงกับการค้นหา</td></tr>';$('page-label').textContent=`${num(view.length)} สินค้า · หน้า ${view.length?page+1:0} / ${Math.ceil(view.length/pageSize)}`;$('prev').disabled=page===0;$('next').disabled=page>=maxPage;$('table-caption').textContent=`เรียงตาม${{sales:'ยอดขาย',net:'ยอดสุทธิ',units:'จำนวนขาย'}[sort]}${descending?'มากไปน้อย':'น้อยไปมาก'} · ค้นหาเฉพาะตาราง`;
}
function openProduct(code){const p=current.products.find(x=>x.code===code);if(!p)return;$('detail-title').textContent=p.name;$('detail-code').textContent='StockCode: '+p.code;$('detail-values').innerHTML=`<dt>ยอดขาย</dt><dd>${money(p.sales)}</dd><dt>ยอดยกเลิก</dt><dd>${money(p.cancel)}</dd><dt>ยอดสุทธิ</dt><dd>${money(p.net)}</dd><dt>จำนวนขาย</dt><dd>${num(p.units)} หน่วย</dd><dt>ราคาเฉลี่ยถ่วงน้ำหนัก</dt><dd>${money(p.price*1000)}</dd><dt>รายการขาย</dt><dd>${num(p.lines)} แถว</dd>`;$('detail').showModal();}
function selectCountry(country){if(!country||!dashboard.countries.includes(country))return;$('country').value=country;update();toast('กรองประเทศ: '+country);}
function selectMonth(month){$('from').value=month;$('to').value=month;update();toast('ดูข้อมูลเดือน '+labelMonth(month));}
function exportCSV(){if(!current)return;const safe=v=>'"'+String(typeof v==='string'&&/^[=+\-@\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';const header=['StockCode','Description','SalesGBP','CancellationGBP','NetGBP','SalesUnits','SalesLines'];const lines=view.map(p=>[p.code,p.name,p.sales/1000,p.cancel/1000,p.net/1000,p.units,p.lines].map(safe).join(','));const blob=new Blob(['\uFEFF'+header.join(',')+'\r\n'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`retail_${$('from').value}_${$('to').value}_${$('country').value||'all'}${$('exclude').checked?'_no-outliers':''}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(`ดาวน์โหลด ${num(view.length)} สินค้าตามตัวกรองและคำค้นหา`);}
$('filters').addEventListener('submit',e=>e.preventDefault());for(const id of ['country','from','to','exclude'])$(id).addEventListener('change',update);
$('reset').addEventListener('click',()=>{$('country').value='';$('from').selectedIndex=0;$('to').selectedIndex=$('to').options.length-1;$('exclude').checked=false;$('search').value='';sort='sales';descending=true;update();});
$('search').addEventListener('input',()=>{page=0;updateTable();});$('prev').addEventListener('click',()=>{page--;updateTable();});$('next').addEventListener('click',()=>{page++;updateTable();});
document.querySelectorAll('[data-sort]').forEach(el=>el.addEventListener('click',()=>{descending=sort===el.dataset.sort?!descending:true;sort=el.dataset.sort;page=0;updateTable();}));
$('table-body').addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(b)openProduct(b.dataset.product);});$('close-dialog').addEventListener('click',()=>$('detail').close());$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close();}});
$('export').addEventListener('click',exportCSV);
function setTheme(dark){document.body.classList.toggle('dark',dark);$('theme').setAttribute('aria-pressed',String(dark));try{localStorage.setItem('retail-theme',dark?'dark':'light');}catch{} }
try{setTheme(localStorage.getItem('retail-theme')==='dark');}catch{}
$('theme').addEventListener('click',()=>{setTheme(!document.body.classList.contains('dark'));if(current)update();});
document.querySelectorAll('.side nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.side nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active');}));
async function init(){try{[dashboard,manifest]=await Promise.all([json('web-data/dashboard.json'),json('web-data/cubes/manifest.json')]);for(const c of dashboard.countries){const o=new Option(c,c);$('country').add(o);}for(const m of manifest.months){$('from').add(new Option(labelMonth(m.month),m.month));$('to').add(new Option(labelMonth(m.month),m.month));}$('to').selectedIndex=$('to').options.length-1;await update();}catch(e){$('error').hidden=false;$('error').textContent=`เปิดข้อมูลไม่ได้: ${e.message} โปรดรัน python -m http.server 8000 จากโฟลเดอร์โปรเจกต์`;$('status').textContent='โหลดไม่สำเร็จ';busy(false);}}
init();
