const chartInstances=[];
const palette=['#2d684d','#8aa45b','#c4d49a','#e9bf73','#cc8564','#b6c2b4'];
export function clearCharts(engine){for(const c of chartInstances.splice(0))c.destroy();if(engine==='plotly'&&window.Plotly)for(const id of ['trend','market','ranking','scatter'])Plotly.purge(id);}
export async function renderCharts(engine,data,ctx){
  clearCharts(engine);
  const fg=ctx.theme?'#b7cbbd':'#68776f', grid=ctx.theme?'#334c40':'#edf0e9', bg=ctx.theme?'#1c342b':'#ffffff';
  const top=data.products.filter(p=>p.sales>0).slice(0,10), points=data.products.filter(p=>p.units>0&&p.price>0);
  const markets=data.countries.slice(0,5);if(data.countries.length>5)markets.push(['Other markets',data.countries.slice(5).reduce((s,x)=>s+x[1],0)]);
  const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2}).format(n);
  const short=n=>n>0&&n<1?Number(n.toPrecision(2)).toString():new Intl.NumberFormat('en-GB',{notation:'compact',maximumFractionDigits:1}).format(n);
  if(engine==='chartjs'){
    if(!window.Chart)throw new Error('ไม่พบไฟล์ Chart.js ใน web/shared/vendor');
    Chart.defaults.font.family='Sarabun, Arial, sans-serif';Chart.defaults.font.size=10;Chart.defaults.color=fg;
    const create=(id,type,chartData,options={})=>{
      const box=document.getElementById(id);box.innerHTML='';const canvas=document.createElement('canvas');box.append(canvas);
      const chart=new Chart(canvas,{type,data:chartData,options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{backgroundColor:'#173f31',padding:11,titleFont:{size:11},bodyFont:{size:11}}},scales:type==='doughnut'?{}:{x:{grid:{display:false},border:{display:false},ticks:{maxRotation:0,autoSkip:true}},y:{grid:{color:grid},border:{display:false},ticks:{callback:short}}},...options}});chartInstances.push(chart);return chart;
    };
    create('trend','line',{labels:data.months.map(m=>ctx.month(m.month)),datasets:[{label:'ยอดขาย',data:data.months.map(m=>m.sales/1000),borderColor:'#75994e',backgroundColor:ctx.theme?'#789a4b25':'#d4e4b34d',fill:true,tension:.3,pointRadius:3,pointHoverRadius:6,borderWidth:2.5},{label:'ยอดสุทธิ',data:data.months.map(m=>m.net/1000),borderColor:ctx.theme?'#c7d8c3':'#254e3c',borderDash:[4,4],tension:.3,pointRadius:2,borderWidth:1.5}]},{interaction:{mode:'index',intersect:false},plugins:{legend:{display:true,position:'top',align:'end',labels:{usePointStyle:true,pointStyle:'circle',boxWidth:5,boxHeight:5,padding:18}},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${money(c.parsed.y)}`}}},onClick:(event,els)=>{if(els.length)ctx.selectMonth(data.months[els[0].index].month);}});
    if(markets.length)create('market','doughnut',{labels:markets.map(x=>x[0]),datasets:[{data:markets.map(x=>x[1]/1000),backgroundColor:palette,borderWidth:3,borderColor:bg,hoverOffset:7}]},{cutout:'74%',plugins:{legend:{display:true,position:'bottom',labels:{usePointStyle:true,boxWidth:6,boxHeight:6,padding:13,font:{size:10}}},tooltip:{callbacks:{label:c=>`${money(c.raw)} · ${(c.raw/(data.sales/1000)*100).toFixed(1)}%`}}},onClick:(e,els)=>{if(els.length)ctx.country(markets[els[0].index][0]);}});else document.getElementById('market').innerHTML='<div class="empty">ไม่มีรายการขาย</div>';
    create('ranking','bar',{labels:top.map(p=>p.code),datasets:[{label:'ยอดขาย',data:top.map(p=>p.sales/1000),backgroundColor:top.map((p,i)=>i===0?'#2d684d':'#afc887'),borderRadius:4,barPercentage:.7}]},{indexAxis:'y',scales:{x:{grid:{color:grid},border:{display:false},ticks:{callback:short}},y:{grid:{display:false},border:{display:false}}},plugins:{legend:{display:false},tooltip:{callbacks:{title:items=>top[items[0].dataIndex]?.name,label:c=>money(c.parsed.x)}}},onClick:(e,els)=>{if(els.length)ctx.product(top[els[0].index].code);}});
    create('scatter','scatter',{datasets:[{label:'สินค้า',data:points.map(p=>({x:p.price,y:p.units,code:p.code,name:p.name})),backgroundColor:'#78984f88',borderColor:'#4b775888',pointRadius:3,pointHoverRadius:6}]},{scales:{x:{type:'logarithmic',title:{display:true,text:'ราคาเฉลี่ยถ่วงน้ำหนัก (GBP)'},grid:{color:grid},border:{display:false},ticks:{callback:short}},y:{type:'logarithmic',title:{display:true,text:'จำนวนขาย (หน่วย)'},grid:{color:grid},border:{display:false},ticks:{callback:short}}},plugins:{legend:{display:false},tooltip:{callbacks:{title:items=>items[0]?.raw.name,label:c=>[`${c.raw.code} · ${money(c.raw.x)}`,`จำนวน ${short(c.raw.y)} หน่วย`]}}},onClick:(e,els)=>{if(els.length)ctx.product(points[els[0].index].code);}});
  }else{
    if(!window.Plotly)throw new Error('ไม่พบไฟล์ Plotly.js ใน web/shared/vendor');
    const base={paper_bgcolor:bg,plot_bgcolor:bg,font:{family:'Sarabun, Arial, sans-serif',color:fg,size:10},margin:{t:25,r:12,b:42,l:52},xaxis:{gridcolor:grid,zeroline:false},yaxis:{gridcolor:grid,zeroline:false},showlegend:false,hoverlabel:{font:{family:'Sarabun',size:11},bgcolor:'#173f31',font_color:'#ffffff'}};
    const config={responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d'],toImageButtonOptions:{format:'png',filename:'retail_chart',scale:2}};
    const plot=(id,traces,layout={})=>{document.getElementById(id).innerHTML='';return Plotly.newPlot(id,traces,{...base,...layout},config);};
    await plot('trend',[{x:data.months.map(m=>m.month),y:data.months.map(m=>m.sales/1000),type:'scatter',mode:'lines+markers',name:'ยอดขาย',line:{color:'#78994e',shape:'spline',width:2.5},marker:{size:5},fill:'tozeroy',fillcolor:'#d4e4b333',hovertemplate:'%{x}<br>ยอดขาย £%{y:,.2f}<extra></extra>'},{x:data.months.map(m=>m.month),y:data.months.map(m=>m.net/1000),type:'scatter',mode:'lines+markers',name:'ยอดสุทธิ',line:{color:ctx.theme?'#c7d8c3':'#254e3c',dash:'dot',width:1.5},marker:{size:4},hovertemplate:'%{x}<br>สุทธิ £%{y:,.2f}<extra></extra>'}],{showlegend:true,legend:{orientation:'h',x:1,xanchor:'right',y:1.18},xaxis:{type:'category',tickvals:data.months.map(m=>m.month),ticktext:data.months.map(m=>ctx.month(m.month)),tickangle:0,nticks:7,gridcolor:grid},hovermode:'x unified'});
    document.getElementById('trend').on('plotly_click',e=>ctx.selectMonth(e.points[0].x));
    if(markets.length){await plot('market',[{type:'pie',labels:markets.map(x=>x[0]),values:markets.map(x=>x[1]/1000),hole:.74,sort:false,textinfo:'none',marker:{colors:palette,line:{color:bg,width:3}},hovertemplate:'%{label}<br>£%{value:,.2f} · %{percent}<extra></extra>'}],{showlegend:true,margin:{t:4,r:0,l:0,b:66},legend:{orientation:'h',x:.5,xanchor:'center',y:-.1}});document.getElementById('market').on('plotly_click',e=>ctx.country(e.points[0].label));}else document.getElementById('market').innerHTML='<div class="empty">ไม่มีรายการขาย</div>';
    await plot('ranking',[{type:'bar',orientation:'h',x:top.map(p=>p.sales/1000),y:top.map(p=>p.code),customdata:top.map(p=>p.name),marker:{color:top.map((p,i)=>i===0?'#2d684d':'#afc887')},hovertemplate:'%{customdata}<br>£%{x:,.2f}<extra></extra>'}],{margin:{t:2,l:65,r:12,b:30},yaxis:{type:'category',autorange:'reversed',gridcolor:grid},bargap:.35});
    document.getElementById('ranking').on('plotly_click',e=>ctx.product(e.points[0].y));
    await plot('scatter',[{type:'scatter',mode:'markers',x:points.map(p=>p.price),y:points.map(p=>p.units),customdata:points.map(p=>[p.code,p.name]),marker:{color:'#78984f',opacity:.55,size:6},hovertemplate:'%{customdata[1]}<br>%{customdata[0]} · £%{x:,.2f}<br>%{y:,.0f} หน่วย<extra></extra>'}],{margin:{t:5,l:55,r:10,b:50},xaxis:{type:'log',title:{text:'ราคาเฉลี่ยถ่วงน้ำหนัก (GBP)',standoff:8},gridcolor:grid},yaxis:{type:'log',title:{text:'จำนวนขาย (หน่วย)'},gridcolor:grid}});
    document.getElementById('scatter').on('plotly_click',e=>ctx.product(e.points[0].customdata[0]));
  }
}
